    - name: Install packages using apt
      apt: pkg={{item}} force=yes state=installed
      with_items:
       - zsh
       - tree
       - git
    
    - name: Copy zshrc file
      copy: src=zsh/zshrc dest=/home/{{remote_user}}/.zshrc owner={{remote_user}} group={{remote_user}} mode='u=rw'
    
    - name: Change user's shell to zsh
      shell: chsh {{remote_user}} -s /bin/zsh
      
    - name: Install ohmyzsh (1/2)
      git: repo=https://github.com/robbyrussell/oh-my-zsh.git dest=/home/{{remote_user}}/.oh-my-zsh
    
    - name: Install ohmyzsh (2/2)
      file: path=/home/{{remote_user}}/.oh-my-zsh recurse=true owner={{remote_user}} group={{remote_user}}
