sudo: required
  
language: python

python:
 - 3.5

install:
  - pip install gitpython

before_install:
  - sudo add-apt-repository ppa:ansible/ansible -y && sudo apt-get update 
  
script:
  - sudo apt-get install ansible --force-yes -y
       
deploy:
  - provider: pypi
    user: $PYPI_USER
    password: $PYPI_PASSWORD
    on:
      tags: true
