sudo: required
dist: xenial
language: python
python:
  - "3.4"

before_install:
  - sudo apt-get install  -y --force-yes python3, ansible, python3-yaml, python3-progressbar, python3-setuptools
  
install: 
  - python3 ./setup.py install --prefix=/build