    - name: Remove Numix PPA
      apt_repository: repo='{{item}}' state=absent update_cache=true
      with_items: 
       - ppa:numix/ppa

    - name: Remove packages using apt
      apt: pkg={{item}} force=yes state=absent  
      with_items:
       - numix-folders
       - fonts-powerline
       - numix-gtk-theme
       - numix-icon-theme-circle
       - numix-wallpaper-lightbulb
       - feh

    - name: Remove i3 configuration directory
      file: path=/home/{{remote_user}}/.i3 state=absent

    - name: Reset xfce4 notification theme (1/2)
      lineinfile: dest=/home/{{remote_user}}/.config/xfce4/xfconf/xfce-perchannel-xml/xfce4-notifyd.xml regexp=".*notify-location.*" line="<property name=\"notify-location\" type=\"uint\" value=\"3\"/>"
       
    - name: Reset xfce4 notification theme (1/2)
      lineinfile: dest=/home/{{remote_user}}/.config/xfce4/xfconf/xfce-perchannel-xml/xfce4-notifyd.xml regexp=".*theme.*" line="<property name=\"theme\" type=\"string\" value=\"Greybird\"/>"
    
    - name: Reset xfce4 theme
      lineinfile: dest=/home/{{remote_user}}/.config/xfce4/xfconf/xfce-perchannel-xml/xsettings.xml regexp=".*name=\"ThemeName\".*" line="<property name=\"ThemeName\" type=\"string\" value=\"Greybird\"/>"
      
    - name: Reset xfce4 icon theme
      lineinfile: dest=/home/{{remote_user}}/.config/xfce4/xfconf/xfce-perchannel-xml/xsettings.xml regexp=".*name=\"IconThemeName\".*" line="<property name=\"IconThemeName\" type=\"string\" value=\"elementary-xfce-dark\"/>"
    
    - name: Remove themed fonts   
      file: path=/home/{{remote_user}}/.fonts/{{ item }} state=absent
      with_items:
       - openlogos.ttf
