    - apt: pkg={{item}} force=yes state=installed  
      with_items:
       - i3

    - copy: src={{item}} dest=/home/{{remote_user}}/.config/autostart/ owner={{remote_user}} group={{remote_user}} mode='u=rw'
      with_fileglob:
       - autostart/*

    - file: path=/home/{{remote_user}}/.cache/sessions state=absent
    - file: path=/home/{{remote_user}}/.config/xfce4/xfconf/xfce-perchannel-xml state=directory
    - copy: src=xfce/xfce4-session.xml dest=/home/{{remote_user}}/.config/xfce4/xfconf/xfce-perchannel-xml/xfce4-session.xml owner={{remote_user}}  group={{remote_user}} mode='u=rw'