    - name: Add Albert PPA repositories
      shell: echo 'deb http://download.opensuse.org/repositories/home:/manuelschneid3r/xUbuntu_18.04/ /' > /etc/apt/sources.list.d/home:manuelschneid3r.list

    - name: Add Albert Release Key
      apt_key:
        url: http://download.opensuse.org/repositories/home:/manuelschneid3r/xUbuntu_18.04/Release.key
        state: present

    - name: Update Apt
      shell: sudo apt update

    - name: Install packages using apt
      apt: pkg={{item}} force=yes state=installed  
      with_items:
       - albert
       - aptitude
       - vim
       - python-dev
       - wget
       - python-pip
       - dmenu
       - git
       - git-flow
       - dtrx
       - fasd
       - tree

    - name: Install python packages using pip
      pip: name={{item}} state=present
      with_items:
       - pathlib
       - psutil
       - thefuck
       - i3-py
       - quickswitch-i3
       - cheat

    - name: Changing ownship of Albert configuraiton folder
      file: dest=/home/{{remote_user}}/.config/albert owner={{remote_user}} group={{remote_user}} state=directory
      
    - name: Copy Albert configuration file
      copy: src=albert.conf dest=/home/{{remote_user}}/.config/albert/albert.conf owner={{remote_user}} group={{remote_user}} mode='u=rw' 

    - name: Changing file properties of user configuration folder
      file: dest=/home/{{remote_user}}/.config recurse=true mode="u=rwX"
