    - name: Install packages using apt
      apt_repository: repo='{{item}}' state=present update_cache=true
      with_items: 
       - ppa:aacebedo/fasd
       - ppa:nilarimogard/webupd8
    - apt: pkg={{item}} force=yes state=installed update_cache=true
      with_items:
       - albert
       - aptitude
       - vim
       - python-dev
       - wget
       - cmake
       - build-essential
       - python-pip
       - dmenu
       - git
       - python-software-properties
       - git-flow
       - dtrx
       - fasd
       - zsh
       - tree
    
    - name: Install j4-desktop-menu
      get_url: url=https://github.com/enkore/j4-dmenu-desktop/archive/r2.12.tar.gz dest=/tmp/j4-desktop-menu.tar.gz
    - unarchive: src=/tmp/j4-desktop-menu.tar.gz dest=/tmp/
    - shell: cmake ./ && make install chdir=/tmp/j4-dmenu-desktop-r2.12

    - name: Install python packages using pip
      pip: name={{item}} state=present
      with_items:
       - pathlib
       - psutil
       - thefuck
       - i3-py
       - quickswitch-i3
       - cheat

    - name: Configuring Albert
      file: dest=/home/{{remote_user}}/.config/albert owner={{remote_user}} group={{remote_user}} state=directory mode='u=rwX'
    - copy: src=albert.conf dest=/home/{{remote_user}}/.config/albert/albert.conf owner={{remote_user}} group={{remote_user}} mode='u=rw' 
      
    - name: Configuring zsh
      copy: src=zsh/zshrc dest=/home/{{remote_user}}/.zshrc owner={{remote_user}} group={{remote_user}} mode='u=rw'
    - shell: chsh {{remote_user}} -s /bin/zsh
    - git: repo=https://github.com/robbyrussell/oh-my-zsh.git dest=/home/{{remote_user}}/.oh-my-zsh
    - file: path=/home/{{remote_user}}/.oh-my-zsh recurse=true owner={{remote_user}} group={{remote_user}} mode='u=rwX'
      
      