    - name: Install i3-wm package using apt
      apt: pkg={{item}} force=yes state=installed
      with_items:
       - i3-wm
       - qt5-style-plugins
       - libqt5svg5
       - compton
       - git
       - pkg-config             # libi3ipc-glib && xfce4-i3-workspaces-plugin
       - build-essential        # libi3ipc-glib && xfce4-i3-workspaces-plugin
       - libgtk2.0-dev          # libi3ipc-glib && xfce4-i3-workspaces-plugin
       - xcb-proto              # libi3ipc-glib
       - gtk-doc-tools          # libi3ipc-glib
       - gobject-introspection  # libi3ipc-glib
       - libjson-glib-dev       # libi3ipc-glib
       - xfce4-dev-tools        # xfce4-i3-workspaces-plugin
       - libxfce4ui-*-dev       # xfce4-i3-workspaces-plugin
       - xfce4-panel-dev        # xfce4-i3-workspaces-plugin

    - name: Clone i3ipc-glib git
      git:
        repo: https://github.com/acrisci/i3ipc-glib.git
        dest: /tmp/i3ipc-glib

    - name: Compile i3ipc-glib and install
      shell: cd /tmp/i3ipc-glib && ./autogen.sh --prefix=/usr && make -j && make install

    - name: Clone xfce4-i3-workspaces-plugin git
      git:
        repo: https://github.com/denesb/xfce4-i3-workspaces-plugin.git
        dest: /tmp/xfce4-i3-workspaces-plugin

    - name: Compile xfce4-i3-workspaces-plugin and install
      shell: cd /tmp/xfce4-i3-workspaces-plugin && ./autogen.sh --prefix=/usr && make -j && make install

    - name: Remove dev packages
      apt: pkg={{item}} force=yes state=absent
      with_items:
       - libgtk2.0-dev          # libi3ipc-glib && xfce4-i3-workspaces-plugin
       - xcb-proto              # libi3ipc-glib
       - gtk-doc-tools          # libi3ipc-glib
       - gobject-introspection  # libi3ipc-glib
       - libjson-glib-dev       # libi3ipc-glib
       - xfce4-dev-tools        # xfce4-i3-workspaces-plugin
       - libxfce4ui-*-dev       # xfce4-i3-workspaces-plugin
       - xfce4-panel-dev        # xfce4-i3-workspaces-plugin

    - name: Copy the autostart scripts
      copy: src=autostart/{{item}} dest=/home/{{remote_user}}/.config/autostart/ owner={{remote_user}} group={{remote_user}} mode='u=rw'
      with_items:
       - compton.desktop
       - i3.desktop
       - xfce4-panel.desktop
    
    - name: Remove previous xfce4 sessions
      file: path=/home/{{remote_user}}/.cache/sessions state=absent
    
    - name: Create xfce4 configuration directory in user home
      file: path=/home/{{remote_user}}/.config/xfce4/xfconf/xfce-perchannel-xml state=directory owner={{remote_user}} group={{remote_user}} mode='u=rw'
    
    - name: Copy new xfce4 configuration file
      shell: cp /etc/xdg/xfce4/xfconf/xfce-perchannel-xml/xfce4-session.xml /home/{{remote_user}}/.config/xfce4/xfconf/xfce-perchannel-xml/xfce4-session.xml
    
    - name: Changing xfce4 configuration file ownership
      file: path=/home/{{remote_user}}/.config/xfce4/xfconf/xfce-perchannel-xml/xfce4-session.xml owner={{remote_user}} group={{remote_user}} mode='u=rw'
    
    - name: Create tmp folder
      file: path=/tmp state=directory
    
    - name: Copy xfce4 configuration file patch
      copy: src=xfce/xfce4-session.xml.patch dest=/tmp/ owner={{remote_user}} group={{remote_user}} mode='u=rw'
    
    - name: Apply patch on xfce4 configuration file
      patch: remote_src=True
        src=/tmp/xfce4-session.xml.patch
        dest=/home/{{remote_user}}/.config/xfce4/xfconf/xfce-perchannel-xml/xfce4-session.xml
    
    - name: Hide xfce-wm settings shortcut 
      lineinfile: dest=/usr/share/applications/xfce-wm-settings.desktop state=present line="Hidden=true" 

    - name: Change ownership of ~/.config directory 
      file: path=/home/{{remote_user}}/.config recurse='yes' state='directory' owner={{remote_user}} group={{remote_user}} mode='u=rwX'

