    - apt_key: url=https://dl-ssl.google.com/linux/linux_signing_key.pub state=present
  
    - apt_repository: repo='{{item}}' state=present update_cache=true
      with_items: 
       - deb http://apt.mucommander.com stable main non-free contrib
       - deb http://dl.google.com/linux/chrome/deb/ stable main
 
    - apt: pkg={{item}} force=yes state=installed  
      with_items:
       - aptitude
       - docker.io
       - vim
       - mucommander
       - python-dev
       - conky
       - wget
       - cmake
       - build-essential
       - google-chrome-beta
       - python-pip
       - dmenu
       - feh  
       - git
       - python-software-properties
       - git-flow
   
    - get_url: url=https://github.com/clvv/fasd/archive/1.0.1.tar.gz dest=/tmp/fasd.tar.gz
    - unarchive: src=/tmp/fasd.tar.gz dest=/tmp/
    - shell: make install chdir=/tmp/fasd-1.0.1

    - get_url: url=https://github.com/enkore/j4-dmenu-desktop/archive/r2.12.tar.gz dest=/tmp/j4-desktop-menu.tar.gz
    - unarchive: src=/tmp/j4-desktop-menu.tar.gz dest=/tmp/
    - shell: cmake ./ && make install chdir=/tmp/j4-dmenu-desktop-r2.12

    - pip: name={{item}} state=present
      with_items:
       - pathlib
       - psutil
       - thefuck
       - i3-py
       
    - file: path=/home/{{remote_user}}/.i3 state=directory    
    - git: repo=https://github.com/proxypoke/quickswitch-for-i3.git dest=/tmp/quickswitch
    - shell: cp /tmp/quickswitch/quickswitch.py /home/{{remote_user}}/.i3/quickswitch.py
    - file: path=/home/{{remote_user}}/.i3/quickswitch.py mode='u+rwx' owner={{remote_user}}
