    - name: Install packages using apt
      apt_repository: repo='{{item}}' state=present update_cache=true
      with_items: 
       - ppa:numix/ppa
    - apt: pkg={{item}} force=yes state=installed update_cache=true
      with_items: 
       - lightdm-gtk-greeter
       - fonts-powerline
       - numix-gtk-theme
       - numix-icon-theme-circle
       - numix-plymouth-theme
       - conky
       - feh
       - xfce4-terminal
       - lightdm

    - name: Copy i3 configuration files
      file: path=/home/{{remote_user}}/.i3 state=directory owner={{remote_user}} group={{remote_user}} mode='u=rwX'
    - stat: path=/home/{{remote_user}}/.i3/config
      register: i3_config_exists
    - copy: src=i3/config dest=/home/{{remote_user}}/.i3/config owner={{remote_user}} group={{remote_user}} mode='u=rw'
      when: i3_config_exists.stat.exists == False
             
    - name: Copy conky configurations
      file: path=/home/{{remote_user}}/.conky state=directory owner={{remote_user}} group={{remote_user}} mode='u=rw'    
    - stat: path=/home/{{remote_user}}/.conky/conkyrc_left
      register: conkyrc_left_exists
    - copy: src=conky/conkyrc_left dest=/home/{{remote_user}}/.conky/conkyrc_left owner={{remote_user}} group={{remote_user}} mode='u=rw'
      when: conkyrc_left_exists.stat.exists == False
    - stat: path=/home/{{remote_user}}/.conky/conkyrc_right
      register: conkyrc_right_exists
    - copy: src=conky/conkyrc_right dest=/home/{{remote_user}}/.conky/conkyrc_right owner={{remote_user}} group={{remote_user}} mode='u=rw'
      when: conkyrc_right_exists.stat.exists == False

    - name: Copy compton configuration file
      stat: path=/home/{{remote_user}}/.compton.conf
      register: compton_conf_exists  
    - copy: src=compton/compton.conf dest=/home/{{remote_user}}/.compton.conf owner={{remote_user}} group={{remote_user}} mode='u=rw'
      when: compton_conf_exists.stat.exists == False
    
    - name: Apply xfce theme
      file: path=/home/{{remote_user}}/.config/xfce4/xfconf/xfce-perchannel-xml state=directory owner={{remote_user}} group={{remote_user}} mode='u=rwX'
    - shell: cp -n /etc/xdg/xfce4/xfconf/xfce-perchannel-xml/xsettings.xml /home/{{remote_user}}/.config/xfce4/xfconf/xfce-perchannel-xml/xsettings.xml
    - file: path=/home/{{remote_user}}/.config/xfce4/xfconf/xfce-perchannel-xml/xsettings.xml owner={{remote_user}}  group={{remote_user}} mode='u=rw'
    - lineinfile: dest=/home/{{remote_user}}/.config/xfce4/xfconf/xfce-perchannel-xml/xsettings.xml regexp=".*name=\"ThemeName\".*" line="<property name=\"ThemeName\" type=\"string\" value=\"Numix\"/>"
    - lineinfile: dest=/home/{{remote_user}}/.config/xfce4/xfconf/xfce-perchannel-xml/xsettings.xml regexp=".*name=\"IconThemeName\".*" line="<property name=\"IconThemeName\" type=\"string\" value=\"Numix-Circle\"/>"
    
    - name: Apply xfce notification theme
      copy: src=xfce/xfce4-notifyd.xml dest=/home/{{remote_user}}/.config/xfce4/xfconf/xfce-perchannel-xml/xfce4-notifyd.xml owner={{remote_user}} group={{remote_user}} mode='u=rw'

    - name: Apply lightdm theme
      lineinfile: dest=/etc/lightdm/lightdm-gtk-greeter.conf line='[greeter]'
    - lineinfile: dest=/etc/lightdm/lightdm-gtk-greeter.conf regexp="^theme-name.*" line='theme-name=Numix' insertafter="[greeter]"  state=present
    - lineinfile: dest=/etc/lightdm/lightdm-gtk-greeter.conf regexp="^icon-theme-name.*" line='icon-theme-name=Numix-Circle' insertafter="[greeter]" state=present
    - lineinfile: dest=/etc/lightdm/lightdm-gtk-greeter.conf regexp="^background.*" line='background=/usr/share/backgrounds/Numix_Lightbulb.png' insertafter="[greeter]" state=present
    - lineinfile: dest=/etc/lightdm/lightdm-gtk-greeter.conf regexp="^user-background.*" line='user-background = false' insertafter="[greeter]" state=present
    
    - name: Add themed fonts
      file: path=/home/{{remote_user}}/.fonts state=directory owner={{remote_user}} group={{remote_user}} mode='u=rwX'    
    - stat: path=/home/{{remote_user}}/.fonts/openlogos.ttf
      register: openlogos_exists      
    - copy: src=fonts/openlogos.ttf dest=/home/{{remote_user}}/.fonts/openlogos.ttf owner={{remote_user}} group={{remote_user}} mode='u=rw'
      when: openlogos_exists.stat.exists == False
          
    - name: Copy desktop background
      copy: src=xfce/Numix_Lightbulb.png dest=/usr/share/backgrounds/Numix_Lightbulb.png  owner=root  group=root mode='a=r'
